# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z\016/protocol/base'),
  serialized_pb=_b('\n\nbase.proto\".\n\tClientMsg\x12\x10\n\x08\x43lientID\x18\x01 \x01(\x0c\x12\x0f\n\x07Payload\x18\x02 \x01(\x0c\"\x1c\n\tServerMsg\x12\x0f\n\x07Payload\x18\x01 \x01(\x0c\"!\n\x0cHandshakeMsg\x12\x11\n\tPublicKey\x18\x01 \x01(\x0c\"$\n\x08\x45rrorMsg\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.ErrorType\"\x9c\x01\n\x07\x42\x61seMsg\x12\x1d\n\x08\x45rrorMsg\x18\x01 \x01(\x0b\x32\t.ErrorMsgH\x00\x12%\n\x0cHandshakeMsg\x18\x02 \x01(\x0b\x32\r.HandshakeMsgH\x00\x12\x1f\n\tClientMsg\x18\x03 \x01(\x0b\x32\n.ClientMsgH\x00\x12\x1f\n\tServerMsg\x18\x04 \x01(\x0b\x32\n.ServerMsgH\x00\x42\t\n\x07MsgType*/\n\tErrorType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x15\n\x11HANDSHAKE_EXPIRED\x10\x01\x42\x10Z\x0e/protocol/baseb\x06proto3')
)

_ERRORTYPE = _descriptor.EnumDescriptor(
  name='ErrorType',
  full_name='ErrorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HANDSHAKE_EXPIRED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=324,
  serialized_end=371,
)
_sym_db.RegisterEnumDescriptor(_ERRORTYPE)

ErrorType = enum_type_wrapper.EnumTypeWrapper(_ERRORTYPE)
UNKNOWN = 0
HANDSHAKE_EXPIRED = 1



_CLIENTMSG = _descriptor.Descriptor(
  name='ClientMsg',
  full_name='ClientMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ClientID', full_name='ClientMsg.ClientID', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Payload', full_name='ClientMsg.Payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=60,
)


_SERVERMSG = _descriptor.Descriptor(
  name='ServerMsg',
  full_name='ServerMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Payload', full_name='ServerMsg.Payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=90,
)


_HANDSHAKEMSG = _descriptor.Descriptor(
  name='HandshakeMsg',
  full_name='HandshakeMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PublicKey', full_name='HandshakeMsg.PublicKey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=125,
)


_ERRORMSG = _descriptor.Descriptor(
  name='ErrorMsg',
  full_name='ErrorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ErrorMsg.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=163,
)


_BASEMSG = _descriptor.Descriptor(
  name='BaseMsg',
  full_name='BaseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrorMsg', full_name='BaseMsg.ErrorMsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HandshakeMsg', full_name='BaseMsg.HandshakeMsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ClientMsg', full_name='BaseMsg.ClientMsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ServerMsg', full_name='BaseMsg.ServerMsg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MsgType', full_name='BaseMsg.MsgType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=166,
  serialized_end=322,
)

_ERRORMSG.fields_by_name['type'].enum_type = _ERRORTYPE
_BASEMSG.fields_by_name['ErrorMsg'].message_type = _ERRORMSG
_BASEMSG.fields_by_name['HandshakeMsg'].message_type = _HANDSHAKEMSG
_BASEMSG.fields_by_name['ClientMsg'].message_type = _CLIENTMSG
_BASEMSG.fields_by_name['ServerMsg'].message_type = _SERVERMSG
_BASEMSG.oneofs_by_name['MsgType'].fields.append(
  _BASEMSG.fields_by_name['ErrorMsg'])
_BASEMSG.fields_by_name['ErrorMsg'].containing_oneof = _BASEMSG.oneofs_by_name['MsgType']
_BASEMSG.oneofs_by_name['MsgType'].fields.append(
  _BASEMSG.fields_by_name['HandshakeMsg'])
_BASEMSG.fields_by_name['HandshakeMsg'].containing_oneof = _BASEMSG.oneofs_by_name['MsgType']
_BASEMSG.oneofs_by_name['MsgType'].fields.append(
  _BASEMSG.fields_by_name['ClientMsg'])
_BASEMSG.fields_by_name['ClientMsg'].containing_oneof = _BASEMSG.oneofs_by_name['MsgType']
_BASEMSG.oneofs_by_name['MsgType'].fields.append(
  _BASEMSG.fields_by_name['ServerMsg'])
_BASEMSG.fields_by_name['ServerMsg'].containing_oneof = _BASEMSG.oneofs_by_name['MsgType']
DESCRIPTOR.message_types_by_name['ClientMsg'] = _CLIENTMSG
DESCRIPTOR.message_types_by_name['ServerMsg'] = _SERVERMSG
DESCRIPTOR.message_types_by_name['HandshakeMsg'] = _HANDSHAKEMSG
DESCRIPTOR.message_types_by_name['ErrorMsg'] = _ERRORMSG
DESCRIPTOR.message_types_by_name['BaseMsg'] = _BASEMSG
DESCRIPTOR.enum_types_by_name['ErrorType'] = _ERRORTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientMsg = _reflection.GeneratedProtocolMessageType('ClientMsg', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTMSG,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:ClientMsg)
  ))
_sym_db.RegisterMessage(ClientMsg)

ServerMsg = _reflection.GeneratedProtocolMessageType('ServerMsg', (_message.Message,), dict(
  DESCRIPTOR = _SERVERMSG,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:ServerMsg)
  ))
_sym_db.RegisterMessage(ServerMsg)

HandshakeMsg = _reflection.GeneratedProtocolMessageType('HandshakeMsg', (_message.Message,), dict(
  DESCRIPTOR = _HANDSHAKEMSG,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:HandshakeMsg)
  ))
_sym_db.RegisterMessage(HandshakeMsg)

ErrorMsg = _reflection.GeneratedProtocolMessageType('ErrorMsg', (_message.Message,), dict(
  DESCRIPTOR = _ERRORMSG,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:ErrorMsg)
  ))
_sym_db.RegisterMessage(ErrorMsg)

BaseMsg = _reflection.GeneratedProtocolMessageType('BaseMsg', (_message.Message,), dict(
  DESCRIPTOR = _BASEMSG,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:BaseMsg)
  ))
_sym_db.RegisterMessage(BaseMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
