# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z\r/protocol/app'),
  serialized_pb=_b('\n\tapp.proto\"V\n\x07\x43ommand\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x0b\n\x03\x65nv\x18\x03 \x03(\t\x12\r\n\x05stdin\x18\x04 \x01(\x0c\x12\x15\n\rtimeoutMillis\x18\x05 \x01(\x03\"T\n\rCommandResult\x12\x11\n\tcommandId\x18\x01 \x01(\x04\x12\x10\n\x08\x65xitCode\x18\x02 \x01(\x05\x12\x0e\n\x06stdout\x18\x03 \x01(\x0c\x12\x0e\n\x06stderr\x18\x04 \x01(\x0c\",\n\x0e\x43ommandListMsg\x12\x1a\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x08.Command\">\n\x14\x43ommandResultListMsg\x12&\n\x0e\x63ommandResults\x18\x01 \x03(\x0b\x32\x0e.CommandResult\"\x13\n\x11GetCommandListMsg\"}\n\x08\x41gentMsg\x12\x35\n\x14\x43ommandResultListMsg\x18\x01 \x01(\x0b\x32\x15.CommandResultListMsgH\x00\x12/\n\x11GetCommandListMsg\x18\x02 \x01(\x0b\x32\x12.GetCommandListMsgH\x00\x42\t\n\x07MsgType\"\x0c\n\nSuccessMsg\"`\n\x05LPMsg\x12!\n\nSuccessMsg\x18\x01 \x01(\x0b\x32\x0b.SuccessMsgH\x00\x12)\n\x0e\x43ommandListMsg\x18\x02 \x01(\x0b\x32\x0f.CommandListMsgH\x00\x42\t\n\x07MsgTypeB\x0fZ\r/protocol/appb\x06proto3')
)




_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Command.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='Command.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env', full_name='Command.env', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdin', full_name='Command.stdin', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeoutMillis', full_name='Command.timeoutMillis', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=99,
)


_COMMANDRESULT = _descriptor.Descriptor(
  name='CommandResult',
  full_name='CommandResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandId', full_name='CommandResult.commandId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exitCode', full_name='CommandResult.exitCode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdout', full_name='CommandResult.stdout', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='CommandResult.stderr', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=185,
)


_COMMANDLISTMSG = _descriptor.Descriptor(
  name='CommandListMsg',
  full_name='CommandListMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commands', full_name='CommandListMsg.commands', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=231,
)


_COMMANDRESULTLISTMSG = _descriptor.Descriptor(
  name='CommandResultListMsg',
  full_name='CommandResultListMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandResults', full_name='CommandResultListMsg.commandResults', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=295,
)


_GETCOMMANDLISTMSG = _descriptor.Descriptor(
  name='GetCommandListMsg',
  full_name='GetCommandListMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=316,
)


_AGENTMSG = _descriptor.Descriptor(
  name='AgentMsg',
  full_name='AgentMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CommandResultListMsg', full_name='AgentMsg.CommandResultListMsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GetCommandListMsg', full_name='AgentMsg.GetCommandListMsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MsgType', full_name='AgentMsg.MsgType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=318,
  serialized_end=443,
)


_SUCCESSMSG = _descriptor.Descriptor(
  name='SuccessMsg',
  full_name='SuccessMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=457,
)


_LPMSG = _descriptor.Descriptor(
  name='LPMsg',
  full_name='LPMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SuccessMsg', full_name='LPMsg.SuccessMsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CommandListMsg', full_name='LPMsg.CommandListMsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MsgType', full_name='LPMsg.MsgType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=459,
  serialized_end=555,
)

_COMMANDLISTMSG.fields_by_name['commands'].message_type = _COMMAND
_COMMANDRESULTLISTMSG.fields_by_name['commandResults'].message_type = _COMMANDRESULT
_AGENTMSG.fields_by_name['CommandResultListMsg'].message_type = _COMMANDRESULTLISTMSG
_AGENTMSG.fields_by_name['GetCommandListMsg'].message_type = _GETCOMMANDLISTMSG
_AGENTMSG.oneofs_by_name['MsgType'].fields.append(
  _AGENTMSG.fields_by_name['CommandResultListMsg'])
_AGENTMSG.fields_by_name['CommandResultListMsg'].containing_oneof = _AGENTMSG.oneofs_by_name['MsgType']
_AGENTMSG.oneofs_by_name['MsgType'].fields.append(
  _AGENTMSG.fields_by_name['GetCommandListMsg'])
_AGENTMSG.fields_by_name['GetCommandListMsg'].containing_oneof = _AGENTMSG.oneofs_by_name['MsgType']
_LPMSG.fields_by_name['SuccessMsg'].message_type = _SUCCESSMSG
_LPMSG.fields_by_name['CommandListMsg'].message_type = _COMMANDLISTMSG
_LPMSG.oneofs_by_name['MsgType'].fields.append(
  _LPMSG.fields_by_name['SuccessMsg'])
_LPMSG.fields_by_name['SuccessMsg'].containing_oneof = _LPMSG.oneofs_by_name['MsgType']
_LPMSG.oneofs_by_name['MsgType'].fields.append(
  _LPMSG.fields_by_name['CommandListMsg'])
_LPMSG.fields_by_name['CommandListMsg'].containing_oneof = _LPMSG.oneofs_by_name['MsgType']
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['CommandResult'] = _COMMANDRESULT
DESCRIPTOR.message_types_by_name['CommandListMsg'] = _COMMANDLISTMSG
DESCRIPTOR.message_types_by_name['CommandResultListMsg'] = _COMMANDRESULTLISTMSG
DESCRIPTOR.message_types_by_name['GetCommandListMsg'] = _GETCOMMANDLISTMSG
DESCRIPTOR.message_types_by_name['AgentMsg'] = _AGENTMSG
DESCRIPTOR.message_types_by_name['SuccessMsg'] = _SUCCESSMSG
DESCRIPTOR.message_types_by_name['LPMsg'] = _LPMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  ))
_sym_db.RegisterMessage(Command)

CommandResult = _reflection.GeneratedProtocolMessageType('CommandResult', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDRESULT,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:CommandResult)
  ))
_sym_db.RegisterMessage(CommandResult)

CommandListMsg = _reflection.GeneratedProtocolMessageType('CommandListMsg', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDLISTMSG,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:CommandListMsg)
  ))
_sym_db.RegisterMessage(CommandListMsg)

CommandResultListMsg = _reflection.GeneratedProtocolMessageType('CommandResultListMsg', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDRESULTLISTMSG,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:CommandResultListMsg)
  ))
_sym_db.RegisterMessage(CommandResultListMsg)

GetCommandListMsg = _reflection.GeneratedProtocolMessageType('GetCommandListMsg', (_message.Message,), dict(
  DESCRIPTOR = _GETCOMMANDLISTMSG,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:GetCommandListMsg)
  ))
_sym_db.RegisterMessage(GetCommandListMsg)

AgentMsg = _reflection.GeneratedProtocolMessageType('AgentMsg', (_message.Message,), dict(
  DESCRIPTOR = _AGENTMSG,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:AgentMsg)
  ))
_sym_db.RegisterMessage(AgentMsg)

SuccessMsg = _reflection.GeneratedProtocolMessageType('SuccessMsg', (_message.Message,), dict(
  DESCRIPTOR = _SUCCESSMSG,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:SuccessMsg)
  ))
_sym_db.RegisterMessage(SuccessMsg)

LPMsg = _reflection.GeneratedProtocolMessageType('LPMsg', (_message.Message,), dict(
  DESCRIPTOR = _LPMSG,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:LPMsg)
  ))
_sym_db.RegisterMessage(LPMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
